### ISSUE TITLE
Chrome version 60.0.3112.78 cannot generate pdf

### ISSUE THREAD

**Issue by kla7016** [bpampuch/pdfmake#1096]
like this pic below
![20615379_1450780808300876_261773707_o](https://user-images.githubusercontent.com/8650457/28857529-72000586-7774-11e7-87f6-340d6be9aebe.png)

**Comment by liborm85** [comment]
Please attach simple example for reproduce your problem.

**Comment by nthnmldr** [comment]
we had the same issue.  We were running pdfmake v0.1.20.  After upgrading to the latest version of pdfmake v0.1.32, pdfs generated fine in Chrome 60.

**Comment by kla7016** [comment]
I already upgraded to latest version of pafmake. But it's still have error like below pic
![20630071_1451957014849922_1681378405_o](https://user-images.githubusercontent.com/8650457/28909361-5d951a30-7852-11e7-9728-6a0c17ce2bf1.png)

**Comment by liborm85** [comment]
Tested with Chrome version 60.0.3112.78 and 60.0.3112.90 and with latest pdfmake. Download, open and print works ok.

From the printscreen, it is clear that this error does not generate pdfmake because it does not use `data:application/pdf:base64`. Pdfmake using `blob:`.

**Comment by kla7016** [comment]
Thank you @liborm85 it works ok when using blob but it not work with adblock extension of chrome.

**Comment by liborm85** [comment]
Yes, it is known. Supported browsers and restrictions is described here - https://github.com/bpampuch/pdfmake/issues/800

**Comment by se21kim** [comment]
Thank you @liborm85. I had been through the same problem with pdfmake ver 0.1.17.  When I used the version 0.1.17 , the same error message showed up. (data:application/pdf:base64). But as liborm85's recommendation, I updated pdfmake version as the latest 0.1.32.     And Then the problem was solved.

**Comment by roydec** [comment]
Hi, I still have the problem as kl7016 had. I all worked before up until v59 of Chrome.
the error I'm getting is the same as kl7016, it starts with data:application/pdf:base64.
there is no add blocker in chrome:\\extenstoins. 
Please advise. Should I alter my code?

With regards

**Comment by se21kim** [comment]
SINCE Now i'm writing on the phone, MESSSGES are simple.
1.Check your pdfmake version.2.Update it.After you have same version pdfmake,If you had same version, 3. Update your bower or npm.Current latest version is 0.1.32.And then reupdate pdfmake..
It would works..


삼성 갤럭시 스마트폰에서 보냈습니다.
-------- 원본 이메일 --------보낸 사람: roydec <notifications@github.com> 날짜: 17/8/10  오후 4:58  (GMT+09:00) 받은 사람: bpampuch/pdfmake <pdfmake@noreply.github.com> 참조: se21kim <se21kim@naver.com>, Comment <comment@noreply.github.com> 제목: Re: [bpampuch/pdfmake] Chrome version 60.0.3112.78 cannot generate pdf (#1096) 
Hi, I still have the problem as kl7016 had. I all worked before up until v59 of Chrome.

the error I'm getting is the same as kl7016, it starts with data:application/pdf:base64.

there is no add blocker in chrome:\extenstoins.

Please advise. Should I alter my code?
With regards

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/bpampuch/pdfmake","title":"bpampuch/pdfmake","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/bpampuch/pdfmake"}},"updates":{"snippets":[{"icon":"PERSON","message":"@roydec in #1096: Hi, I still have the problem as kl7016 had. I all worked before up until v59 of Chrome.\r\nthe error I'm getting is the same as kl7016, it starts with data:application/pdf:base64.\r\nthere is no add blocker in chrome:\\\\extenstoins. \r\nPlease advise. Should I alter my code?\r\n\r\nWith regards"}],"action":{"name":"View Issue","url":"https://github.com/bpampuch/pdfmake/issues/1096#issuecomment-321479904"}}}

**Comment by roydec** [comment]
Great, thanks a lot, seems I had a caching problem.

**Comment by JagadishKumarP** [comment]
Working like a charm :) the new blob 'd url looks great..

**Comment by osleyhc** [comment]
Hello everyone, I still have the problem as kl7016 had. It worked perfect before up until version60 of Chrome. When I updated to  latest version is 0.1.32, the error disappears, but the new tab is open and closet instantaneous.
I'm using angularjs 1.5, and generation the pdf from ui-grid, below is a piece of code of gridOptions.

$scope.gridOptions = {
                    data: result,
                    enableFiltering: true,                    
                    enableGridMenu: true,
                    onRegisterApi: function (gridApi) {
                        $scope.gridApi = gridApi;
                    }   

function exportToPDF() {
            $scope.gridApi.exporter.pdfExport('visible', 'visible');
        }
How can I alter my code?
Thanks in advance

**Comment by Wabbala** [comment]
Did you turn off you ad blocker/popup blocker?

**Comment by osleyhc** [comment]
You git it, thanks a lot!!! The AdBlock was the cause of close the new tab, in previous version of 60 it was working properly.
