### ISSUE TITLE
Cannot read property 'TYPED_ARRAY_SUPPORT' of undefined (pdfmake v0.1.32)

### ISSUE THREAD

**Issue by davidbeers** [bpampuch/pdfmake#1100]
I've seen that https://github.com/bpampuch/pdfmake/issues/624 which first reports this issue is closed with note that a fix was released in Dec '16. However I see this error running in an Angular 2 application and webpack with pdfmake 0.1.32.

```
let pdfMake = require('pdfmake/build/pdfmake.js');
require('pdfmake/build/vfs_fonts.js');

@Component({
...
})
export class PdfReportComponent implements OnInit {
    ngOnInit() {
        let docDefinition = { content: 'PDF is in the house!' };
        pdfMake.createPdf(docDefinition).open();
    }
}
```

Stacktrace:
```
pdfmake.js:48 Uncaught TypeError: Cannot read property 'TYPED_ARRAY_SUPPORT' of undefined
    at Object.eval (webpack:///./~/pdfmake/build/pdfmake.js?:48:38)
    at Object.exports.byteLength (webpack:///./~/pdfmake/build/pdfmake.js?:169:32)
    at __webpack_require__ (webpack:///./~/pdfmake/build/pdfmake.js?:10:27)
    at Object.eval (webpack:///./~/pdfmake/build/pdfmake.js?:20:2086)
    at __webpack_require__ (webpack:///./~/pdfmake/build/pdfmake.js?:10:27)
    at Object.eval (webpack:///./~/pdfmake/build/pdfmake.js?:16:267)
    at Object.eval (webpack:///./~/pdfmake/build/pdfmake.js?:16:320)
    at __webpack_require__ (webpack:///./~/pdfmake/build/pdfmake.js?:10:27)
    ...
```
What am I missing, please?

**Comment by jovabe** [comment]
Having the same issue.

**Comment by ldevalbray** [comment]
Same issue here:s

**Comment by ldevalbray** [comment]
@liborm85 It would be really cool to fix it ! :D Thank you for your awesome work anyway

**Comment by liborm85** [comment]
In issue https://github.com/bpampuch/pdfmake/issues/624 it was fixed by update webpack.

According to comment above is now error on other line (line 48), but on this line is this code:
```js
__webpack_require__.p = "";
```
This has nothing to do with array. I do not know how to fix this error now.

**Comment by ldevalbray** [comment]
![image](https://user-images.githubusercontent.com/16904604/31586934-4702a898-b1d0-11e7-913f-12ed5593d651.png)
My logs says the error is there

**Comment by ldevalbray** [comment]
Okay, I managed to solve it.
So, for anyone using webpack : 

Import pdfMake like so : 
`import pdfMake from "pdfmake/build/pdfmake";
import pdfFonts from "pdfmake/build/vfs_fonts";
pdfMake.vfs = pdfFonts.pdfMake.vfs;`

plus adding the config in webpack
`exclude: [
/node_modules/,
/pdfmake.js$/ <--
]`

Good luck !

**Comment by liborm85** [comment]
Solution added to readme by commit https://github.com/bpampuch/pdfmake/commit/4ad3c8d92425dcd8f458d3b7f86e30d4f6da6c09.

**Comment by mkaisercross** [comment]
I tried this but I am still getting the same error. Here is my config file.

`var path = require('path');

module.exports = {
  plugins: [
    // your custom plugins                                                                                                       
  ],
  module: {
    rules: [
        {
            test: /\.js?$/,
            loader: 'babel-loader',
            exclude: [/node_modules/, /pdfmake.js/ ]
        },
        {
            test: /\.scss$/,
            loaders: ["style-loader", "css-loader", "sass-loader"]
            //exclude: path.resolve(__dirname, 'src/app')                                                                        
        },
        {
            test: /\.(ttf|otf|eot|svg|woff(2)?)(\?[a-z0-9]+)?$/,
            loader: 'file-loader?name=fonts/[name].[ext]'
        }

    ]
  },
  resolve: {
        modules: [
            "browserify_components",
            "bower_components",
            "node_modules"
        ],
      extensions: ['.js','.jsx','.json'],
  },
}
`

**Comment by barocsi** [comment]
same here, still there
