### ISSUE TITLE
Border of td

### ISSUE THREAD

**Issue by zoepage** [bpampuch/pdfmake#197]
Hey,

is there a way to manipulate the border of the TD's like this:
![bildschirmfoto-2015-02-13-um-12 41 07](https://cloud.githubusercontent.com/assets/562354/6186725/ba9eb5fc-b37d-11e4-921f-c1494e4cc029.png)

So the colour of [1][0] would be e.g. white,
[1][1] would be gray?

**Comment by jthoenes** [comment]
Have a look at the table example in the playground: http://pdfmake.org/playground.html

You can specify a set of functions to select vertical and horizontal lines 

````javascript
  hLineWidth: function(i, node) { return (i === 0 || i === node.table.body.length) ? 2 : 1;},
  vLineWidth: function(i, node) { return (i === 0 || i === node.table.widths.length) ? 2 : 1; },
  hLineColor: function(i, node) {return (i === 0 || i === node.table.body.length) ? 'black' : 'gray'; },
  vLineColor: function(i, node) { return (i === 0 || i === node.table.widths.length) ? 'black' : 'gray';}
}
````

**Comment by zoepage** [comment]
hey @jthoenes!
thanks for your answer. :)

But this is only the definition for the whole not partial horizontal line, right?

**Comment by jthoenes** [comment]
Ah, I see what you mean. So you would need a second index parameter I guess?

**Comment by zoepage** [comment]
Exactly :)

**Comment by cat0rgi0** [comment]
I have found a solution like here:

https://github.com/bpampuch/pdfmake/pull/194

**Comment by zoepage** [comment]
@cat0rgi0 #194 is just for nested cells right? Or does it also work with just one?

**Comment by cat0rgi0** [comment]
@zoepage i had a problem with border cell of a nested table but  solution #194 works fine for any kind of table object

**Comment by zoepage** [comment]
@cat0rgi0 I just got errors (unresolved promise). Maybe I just got something wrong... 

Like in the example: for 2 row, 3 cols:
````
borderLines: [[0,1,0],[1,1,1],[1,1,1]]
````
Is this for one row with 3 cols or...?

**Comment by cat0rgi0** [comment]
In the follow example we have a table with  3 columns and 2 rows:

             borderLines: [[0,1,0],[1,1,1],[1,1,1] ],
             borderCols:[[0,1,1,0],[1,1,1,1]] 

bordeLines.. [0,1,0 ] represents the first line of table divided for each cell , in this example the first and the third cell haven't lines.
bordeLines ..[1,1,1] ,[1,1,1] : second line and third line,  all of them  are visible.

borderCols:[[0,1,1,0] represents the first column from the left side for each cell of first row. 
borderCols:[1,1,1,1] the second row.

![image](https://cloud.githubusercontent.com/assets/152093/6229166/2c0fc1ce-b6b5-11e4-901f-56c63cceb986.png)

**Comment by zoepage** [comment]
Thanks for the explanation :)

**Comment by bpampuch** [comment]
Hello everybody, I'd like to know your preferences on this. Should we:
a) merge @cat0rgi0 PR
b) update hLineWidth/vLineWidth/hLineColor/vLineColor functions and add another parameter
c) add another pair of functions: lineWidth/lineColor with both (line and column) parameters - these would be optional, so pdfmake would provide backwards compatibility; however lineWidth/lineColor, if provided, would take precedence over hLine*/vLine*

**Comment by jthoenes** [comment]
I like option b) the most.

**Comment by zoepage** [comment]
Me too :)

b) +1
Am 03.03.2015 07:51 schrieb "Johannes Thönes" <notifications@github.com>:

**Comment by cat0rgi0** [comment]
b)

**Comment by compact** [comment]
I think either option b) or c) will be more convenient.

**Comment by compact** [comment]
If any of you are interested, I've implemented individual cell borders in a different way in my fork. I added an optional `border` property on each cell to determine the cell's borders with an array of 4 booleans.

See examples here, under Tables: http://compact.github.io/pdfmake/playground.html

Not submitting a PR at this point because it fails test 161, and the right border breaks in cells with both rowSpan > 1 and colSpan > 1.

**Comment by jmblck** [comment]
Option b, I think it is more flexible

**Comment by villevillegas** [comment]
Hi @compact .
How can I get the result of your example?,,,
I have added 
<script type="text/javascript" src="somePath/pdfmake.js"></script>
<script type="text/javascript" src="somePath/vfs_fonts.js"></script>
but still getting this
![image](https://cloud.githubusercontent.com/assets/7843390/11102945/310982ee-8885-11e5-84d7-69b9ae6c2561.png)
Do I need to add another js files?

BTW pdfmake is awesome...

**Comment by compact** [comment]
@villevillegas I don't know. Are you using the changes in my fork?

It should look like this:

![](https://cloud.githubusercontent.com/assets/498501/11229048/a7d8142e-8d5f-11e5-9acb-088e94237d1e.png)

**Comment by rschramm** [comment]
@compact - Your fork is working great on your playground at github.io.  I created a doc definition without borders on some elements and it looks great.  I downloaded the zip file from github, expanded it, and copied the build directory into my www/lib directory (where all my other libs are), and I am still getting the version where the borders show up.  I did a bower install pdfmake from in the zip file and then copied the pdfmake directory from the bower_components in the zip and getting the same thing.  Does this need to be compiled in some way before it gets deployed?  I saw your changes where to files in the src directory, but I am not sure how to build the package (I am new to grunt/gulp/bower as I come from a traditional java background).  Any help would be appreciated.  Thanks!

**Comment by compact** [comment]
@rschramm Are you downloading from here? https://github.com/compact/pdfmake/tree/master/build You don't need to build/compile it yourself since it's there.

Note that when you do `bower install pdfmake`, you're installing the original library, not the fork.

**Comment by rschramm** [comment]
@compact - No, I was downloading it from your commit link earlier in this thread which went to https://github.com/bpampuch/pdfmake/commit/829d4c2ce4b0ba3274594ef3655704773b0ef241 and from there I went to the download zip file which takes me to https://github.com/bpampuch/pdfmake.git (which is the original version I believe).

With the link you provided, I did download a different version.  Unfortunately, when I use the version (either by copy just the 4 file in build or overwriting the whole pdfmake folder with the one I cloned from your repo, I get the following error message: 

Error: TypeError: pdfMake.createPdf is not a function. (In 'pdfMake.createPdf( docDefinition )', 'pdfMake.createPdf' is undefined)

When I delete your version of pdfmake and re-install the original with bower (bower install pdfmake), the error goes away.  So, looks like I traded one issue (the wrong repo) with another (some kind of issue with the updated pdfmake).

If it helps, I am running this in a native iOS app that built with the ionic framework.

Thoughts?

Thanks,

Rich

**Comment by villevillegas** [comment]
Yes, I have done the same as @rschramm , but I have gotten the same error

**Comment by rschramm** [comment]
@villevillegas - did you mean to say you *DID* get the same error, or did *NOT* get the same error?  Your message was unclear.  Please let me know as I am wondering if this is my issue or a bug in this build.

**Comment by villevillegas** [comment]
the same 
![image](https://cloud.githubusercontent.com/assets/7843390/11424388/5ca4f01c-9412-11e5-98e6-83789d870ccf.png).

Sorry if my message wasn't unclear

**Comment by compact** [comment]
@rschramm @villevillegas It was my mistake - I forgot that I had removed lodash from the build for my own needs. Try again and let me know of any further problems.

**Comment by rschramm** [comment]
@compact - just tried it out and it is working perfectly.  Thanks much, Chris, for creating this fork and for addressing that last issue.  @villevillegas - good to luck to you as well.

Have a great day!

Rich

**Comment by villevillegas** [comment]
Hi, now it works,, thank you so much... :)

**Comment by liborm85** [comment]
@bpampuch option b) and c) is flexible but only in static tables or simple dynamic tables. If I generating more difficult content of table dynamically need to be able to set border in each cell in data. Of course it would be best to have the possibility of a combination of both.

But as first step, I used idea @compact fork for borders and rewrote and fix bugs with colSpan/rowSpan and much more. Now it works fine. PR is #493.

**Comment by csvan** [comment]
Any news on this merge?

**Comment by solidet** [comment]
I have been waiting for the cell border feature to be merged. Peace :smile:

**Comment by RLTmultimedia** [comment]
+1

**Comment by liborm85** [comment]
PR https://github.com/bpampuch/pdfmake/pull/493 merged. :)

**Comment by liborm85** [comment]
Version released.
