### ISSUE TITLE
build fail babel-loader (Module parse failed: Unexpected token)

### ISSUE THREAD

**Issue by PokerJava** [bpampuch/pdfmake#2501]
<img width="1319" alt="Screenshot 2565-11-05 at 14 59 56" src="https://user-images.githubusercontent.com/26649959/200110030-74f881e2-78bf-4977-8787-acb092be767c.png">

**Comment by PokerJava** [comment]
got same issue https://stackoverflow.com/questions/74323826/module-parse-failed-unexpected-token-257106-you-may-need-an-appropriate-load#new-answer

**Comment by tushar-chauhan** [comment]
@PokerJava Ran into same issue today morning. Did you find any solution for this?

**Comment by PokerJava** [comment]
still don't know the problem think it might be npm version

**Comment by vmurillo** [comment]
I think it is due to a change in my webpack options, I had to fork this repo and remove the comments at the origin of this problem.

For a reason, I don't know, the comments like [this](https://github.com/Doctocliq/pdfmake/commit/c4370d0437eb12ca85bb05f9853d24c0d927e0d0) are being transformed to an ill-formed js, causing this error

**Comment by obrador** [comment]
Hi, I noticed this error today (I posted it to another issue #2502). For me it worked fine since I upgraded from Angular 11 to 14. I was using v.0.2.2 with Angular 11 without problems. I upgraded to Angular 14 and this error appeared, then I updated Pdfmaker to 0.2.6, but the problem still persists. Hope it helps.

**Comment by liborm85** [comment]
If is problem with comments in code in babel-loader or Angular, can be used minified version (non contain comments) in file `pdfmake.min.js`.

**Comment by PokerJava** [comment]
I found a problem in react

**Comment by subratbhola** [comment]
Getting the same error with below mentioned configuration:
1. Angular 11
2. pdfMake: 0.1.71 and 0.2.4
3. node 10.21.0

Error: Module parse failed: Unexpected token (43456:116)
File was processed with these loaders:
 * ./node_modules/@angular-devkit/build-angular/src/babel/webpack-loader.js
 * ./node_modules/@ngtools/webpack/src/ivy/index.js
You may need an additional loader to handle the result of these loaders.
|            *     not null.
|            */
>           function gen_bitlen(s, desc) /*    deflate_state *s;*/ /*    tree_desc *desc;    /* the tree descriptor */*/{
|             var tree = desc.dyn_tree;
|             var max_code = desc.max_code;
Error: Module parse failed: Unexpected token (71044:112)
File was processed with these loaders:
 * ./node_modules/@angular-devkit/build-angular/src/babel/webpack-loader.js
 * ./node_modules/@ngtools/webpack/src/ivy/index.js
You may need an additional loader to handle the result of these loaders.
|        */
| 
>       function gen_bitlen(s, desc) /*    deflate_state *s;*/ /*    tree_desc *desc;    /* the tree descriptor */*/{
|         var tree = desc.dyn_tree;
|         var max_code = desc.max_code;


Team pdfMake , requesting you to share the feedback ASAP.

**Comment by subratbhola** [comment]
what is the issue @PokerJava

**Comment by PokerJava** [comment]
Getting the same error

**Comment by AnanthiPonnusamyAlfahive** [comment]
Getting same error for react 
![image](https://user-images.githubusercontent.com/110452333/200254589-67e6b83b-f098-43f3-939e-ed0d4b8d1447.png)

**Comment by KevinYobeth** [comment]
Same issue on React 17.0.2 running Node 14.18.2

**Comment by kdRanaa** [comment]
Getting same error.

**Comment by subratbhola** [comment]
did anyone find any solution for the above mentioned issue

**Comment by subratbhola** [comment]
This is a Issue with Babel and webpack as per my find. Please find solutions on those.

**Comment by subratbhola** [comment]
Resolution :

Please install below version in package.json file "resolutions" key.

 "resolutions": {
    "@babel/core": "7.19.6",
    "@babel/generator": "7.19.6",
    "@babel/compat-data": "7.19.4",
    "@babel/helper-compilation-targets": "7.19.3",
    "@babel/helper-create-class-features-plugin": "7.19.0",
    "@babel/helper-module-transforms": "7.19.6"
  }

**Comment by sanchit-narula** [comment]
> 

Can you please also share pdfMake version you're using with this updated resolutions

**Comment by subratbhola** [comment]
> > 
> 
> Can you please also share pdfMake version you're using with this updated resolutions

"pdfmake": "^0.2.4",

**Comment by andreinemikin** [comment]
Downgrading the babel-loader to version 8.2.5 solves the issue.
(I am using CRA, so I did this in package.json - overrides).

**Comment by HoaNguyenTran** [comment]
> **Babel version 7.20.2 contains bug with parsing comments, no way how to fix it in pdfmake.**
> 
> Temporary solution is downgrade babel libraries. Put this lines to `package.json`:
> 
> ```
> "@babel/core": "7.19.6",
> "@babel/generator": "7.19.6",
> "@babel/compat-data": "7.19.4",
> "@babel/helper-compilation-targets": "7.19.3",
> "@babel/helper-create-class-features-plugin":"7.19.0",
> "@babel/helper-module-transforms":"7.19.6",
> ```
> 
> Source: https://stackoverflow.com/a/74327940



> **Babel version 7.20.2 contains bug with parsing comments, no way how to fix it in pdfmake.**
> 
> Temporary solution is downgrade babel libraries. Put this lines to `package.json`:
> 
> ```
> "@babel/core": "7.19.6",
> "@babel/generator": "7.19.6",
> "@babel/compat-data": "7.19.4",
> "@babel/helper-compilation-targets": "7.19.3",
> "@babel/helper-create-class-features-plugin":"7.19.0",
> "@babel/helper-module-transforms":"7.19.6",
> ```
> 
> Source: https://stackoverflow.com/a/74327940

I did it and build success.

**Comment by liborm85** [comment]
Babel bug probably fixed in [Babel v7.20.3](https://github.com/babel/babel/releases/tag/v7.20.3). You can try...

**Comment by PokerJava** [comment]
@liborm85 im use react-scripts-build not use babel

**Comment by liborm85** [comment]
@PokerJava react-scripts uses babel

**Comment by obrador** [comment]
```
npm: 8.19.2
Angular: 14.2.9
pdkmake: 0.2.6
```

Hi, sorry but I haven't been able to solve it. I tried following aproaches:

First, just append this to package.json `dependencies`:
```
"@babel/core": "7.19.6",
"@babel/generator": "7.19.6",
"@babel/compat-data": "7.19.4",
"@babel/helper-compilation-targets": "7.19.3",
"@babel/helper-create-class-features-plugin":"7.19.0",
"@babel/helper-module-transforms":"7.19.6",
```

Also in `resolutions`:

```
"resolutions": {
  "@babel/core": "7.19.6",
  "@babel/generator": "7.19.6",
  "@babel/compat-data": "7.19.4",
  "@babel/helper-compilation-targets": "7.19.3",
  "@babel/helper-create-class-features-plugin": "7.19.0",
  "@babel/helper-module-transforms": "7.19.6"
}
```

Also: 
```
  "overrides": {
    "@angular-devkit/build-angular": {
      "@babel/generator": "7.20.4"
    }
  }
```

And 
```
  "overrides": {
    "@angular-devkit/build-angular": {
      "@babel/generator": "7.19.6"
    }
  }
```

I also tried different combinations of the above. After each change in package.json I did a `npm i`. I tried also to completely remove node_modules/ and package-lock.json. Error persists.
